#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{	
	enum WINMODE : int { WINMODE_FULL, WINMODE_WINDOW, WINMODE_END };

	enum MOUSEKEYSTATE : int { MOUSEKEY_LEFTBUTTON, MOUSEKEY_RIGHTBUTTON, MOUSEKEY_WHEEL, MOUSEKEYSTATE_END };
	enum MOUSEMOVESTATE : int { MOUSEMOVE_X, MOUSEMOVE_Y, MOUSEMOVE_WHEEL, MOUSEMOVESTATE_END };
	enum KEYSTATE : int { KEY_UP, KEY_PRESSED, KEY_DOWN, KEY_RELEASED };

	enum MATRIXROW : int { MATRIXROW_RIGHT, MATRIXROW_UP, MATRIXROW_LOOK, MATRIXROW_POSITION, MATRIXROW_END };
	enum PROTOTYPE : int { PROTOTYPE_OBJECT, PROTOTYPE_COMPONENT };
	enum RENDERGROUP : int { RENDER_PRIORITY, RENDER_SHADOWLIGHT, RENDER_NONBLEND, RENDER_NONLIGHT, RENDER_BLEND, RENDER_UI, RENDERGROUP_END };
	enum LIGHT : int { LIGHT_DIRECTIONAL, LIGHT_POINT, LIGHT_SPOTLIGHT, LIGHT_END };
	enum D3DTS : int { D3DTS_VIEW, D3DTS_PROJECTION, D3DTS_END };
	enum MODELTYPE : int { MODELTYPE_ANIM, MODELTYPE_NONANIM };
	enum COLLISIONTYPE : int {COLLISIONTYPE_AABB, COLLISIONTYPE_OBB, COLLISIONTYPE_SPHERE, COLLISIONTYPE_END};

	enum POINTTYPE : int { A, B, C, POINT_END };
	enum LINETYPE : int { AB, BC, CA, LINE_END };
	enum PICKTYPE : int {PICKTYPE_UI, PICKTYPE_OBJECT, PICKTYPE_TERRAIN, PICKTYPE_GRID, PICKTYPE_PIXEL, PICKTYPE_END };

	enum FACTION : int { FACTION_NEUTRAL, FACTION_PLAYER, FACTION_MONSTER };
	enum UICONTROLTYPE : int { UI_UNKNOWN, UI_LABEL, UI_BUTTON, UI_IMAGE, UI_PANEL };
}
#endif // Engine_Enum_h__
