#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{	
	enum WINMODE : int { FULL, WIN, WINMODE_END };

	enum MOUSEKEYSTATE : int { LB, RB, KEY_WHEEL, MOUSEKEYSTATE_END };
	enum MOUSEMOVESTATE : int { X, Y, MOVE_WHEEL, MOUSEMOVESTATE_END };
	enum KEYSTATE : int { KEY_UP, KEY_PRESSED, KEY_DOWN, KEY_RELEASED };

	enum STATE : int { RIGHT, UP, LOOK, POSITION, STATE_END };
	enum PROTOTYPE : int { OBJECT, COMPONENT };
	enum RENDERGROUP : int { PRIORITY, NONBLEND, BLEND, UI, RENDERGROUP_END };
	enum LIGHT : int { DIRECTIONAL, LIGHT_POINT, LIGHT_END };
	enum D3DTS : int { VIEW, PROJECTION, D3DTS_END };
	enum MODELTYPE : int { ANIM, NONANIM };
	enum COLLISIONTYPE : int {AABB, OBB, SPHERE, COLLISION_END};

	enum POINTTYPE : int { A, B, C, POINT_END };
	enum LINETYPE : int { AB, BC, CA, LINE_END };
	enum PICKTYPE : int {PICK_UI, PICK_OBJECT, PICK_TERRAIN, PICK_GRID, PICK_END };
}
#endif // Engine_Enum_h__
