#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{	
	//창모드, 전체화면 여부
	enum WINMODE : int { WINMODE_FULL, WINMODE_WINDOW, WINMODE_END };

	//입력
	enum MOUSEKEYSTATE : int { MOUSEKEY_LEFTBUTTON, MOUSEKEY_RIGHTBUTTON, MOUSEKEY_WHEEL, MOUSEKEYSTATE_END };
	enum MOUSEMOVESTATE : int { MOUSEMOVE_X, MOUSEMOVE_Y, MOUSEMOVE_WHEEL, MOUSEMOVESTATE_END };
	enum KEYSTATE : int { KEY_UP, KEY_PRESSED, KEY_DOWN, KEY_RELEASED };

	//행렬 구분
	enum MATRIXROW : int { MATRIXROW_RIGHT, MATRIXROW_UP, MATRIXROW_LOOK, MATRIXROW_POSITION, MATRIXROW_END };
	
	//오브젝트 or 컴포넌트 타입
	enum PROTOTYPE : int { PROTOTYPE_OBJECT, PROTOTYPE_COMPONENT };
	
	//랜더용 묶음
	enum RENDERGROUP : int { RENDER_PRIORITY, RENDER_SHADOWLIGHT, RENDER_NONBLEND, RENDER_NONLIGHT, RENDER_BLEND, RENDER_UI, RENDER_MOUSE, RENDERGROUP_END };
	
	//빛 타입
	enum LIGHT : int { LIGHT_DIRECTIONAL, LIGHT_POINT, LIGHT_SPOTLIGHT, LIGHT_END };
	
	//파이프라인 행렬 타입
	enum D3DTS : int { D3DTS_VIEW, D3DTS_PROJECTION, D3DTS_END };
	
	//모델 애니메이션 여부
	enum MODELTYPE : int { MODELTYPE_ANIM, MODELTYPE_NONANIM };
	
	//충돌체 타입
	enum COLLISIONTYPE : int {COLLISIONTYPE_AABB, COLLISIONTYPE_OBB, COLLISIONTYPE_SPHERE, COLLISIONTYPE_END};

	//네비게이션
	enum POINTTYPE : int { A, B, C, POINT_END };
	enum LINETYPE : int { AB, BC, CA, LINE_END };

	//피킹
	enum PICKTYPE : int {PICKTYPE_UI, PICKTYPE_OBJECT, PICKTYPE_TERRAIN, PICKTYPE_GRID, PICKTYPE_PIXEL, PICKTYPE_END };

	//투사체
	enum FACTION : int { FACTION_NEUTRAL, FACTION_PLAYER, FACTION_MONSTER };
	
	//UI 종류
	enum UITYPE : int { UI_IMAGE, UI_BUTTON, UI_LABEL , UI_PANEL, UI_END};

	//퀘스트 상태
	enum QUEST : int { QUEST_INACTIVE, QUEST_ACTIVE, QUEST_COMPLETED, QUEST_FAILED };
	enum CONTENTS : int { CONTENTS_INACTIVE, CONTENTS_ACTIVE, CONTENTS_COMPLETED, CONTENTS_FAILED };
	enum CONTENTSTYPE : int { CONTENTSTYPE_TRIGGER, CONTENTSTYPE_KILL, CONTENTSTYPE_INTERACT, CONTENTSTYPE_CUSTOM };
	enum EVENTTYPE : int { EVENTTYPE_TRIGGER_IN, EVENTTYPE_TRIGGER_OUT, EVENTTYPE_KILL, EVENTTYPE_INTERACT, EVENTTYPE_CUSTOM };
}
#endif // Engine_Enum_h__
